//! Command/query boundary for riverbeam.
//!
//! Two surfaces share this module:
//!
//! * [`BeamDomain`] — a thin, typed client over a [`BeamWorkerClient`] used by
//!   the example HTTP handlers (`invoke` / `stream` / `resume`).
//! * [`BeamDomainBundle`] — the same boundary exposed as a real
//!   [`riverbase_core::Domain`] (`flrs.beam`) so it mounts in a `RiverbaseApp`
//!   alongside other domains. The command engine bridges `invoke` / `stream` /
//!   `resume` to a [`BeamWorkerClient`] (local in-process, or NATS-backed in
//!   production); the query engine serves the agent / model / session catalog.
//!
//! The engines are hand-written rather than generated by `command_engine!` /
//! `query_resource!`: the latter's dispatch table is closed to in-crate resource
//! names, so a hand-written [`DomainQueryEngine`] is the supported extension
//! point for an out-of-tree domain.

use std::sync::Arc;

use async_trait::async_trait;
use beam_types::{ContentPart, InvokeAuthContext, InvokeRequest};
use riverbase_core::query::{QueryAccess, QueryRequest, QueryResourceKind, QueryRouteMeta};
use riverbase_core::{
    CommandMeta, CommandTarget, Domain, DomainCommandEngine, DomainQueryEngine, EngineContext,
    RiverbaseResult, OpenApiMeta, ScopeMeta,
};
use serde::{Deserialize, Serialize};
use serde_json::{json, Value};
use tokio::sync::RwLock;
use uuid::Uuid;

use crate::authz::{command_activity, subject_from_payload, ActivityAuthorizer, ActivityRequest};
use crate::catalog::Catalog;
use crate::client::BeamWorkerClient;

/// Default namespace for the beam domain.
pub const BEAM_NAMESPACE: &str = "flrs.beam";

const CMD_INVOKE: &str = "invoke";
const CMD_STREAM: &str = "stream";
const CMD_RESUME: &str = "resume";

const RES_AGENT: &str = "agent";
const RES_MODEL: &str = "model";
const RES_SESSION: &str = "agent_session";

/// Inbound payload for `invoke` / `stream` (mirrors `InvokeAgentPayload`).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct InvokePayload {
    pub agent_name: String,
    pub content: Vec<ContentPart>,
    pub session_id: Uuid,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub model_override: Option<String>,
    #[serde(default)]
    pub metadata: Value,
    #[serde(default)]
    pub stream: bool,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub auth_context: Option<InvokeAuthContext>,
}

/// Inbound payload for `resume` (carries the interaction being resumed).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ResumePayload {
    pub agent_name: String,
    pub content: Vec<ContentPart>,
    pub session_id: Uuid,
    pub interaction_id: Uuid,
    pub actions: Vec<beam_types::ActionResponseEnvelope>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub model_override: Option<String>,
    #[serde(default)]
    pub metadata: Value,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub auth_context: Option<InvokeAuthContext>,
}

/// Acknowledgement returned by streaming commands (client then subscribes SSE).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct StreamAck {
    pub request_id: Uuid,
    pub session_id: Uuid,
    pub agent_name: String,
}

/// Command handlers backed by a [`BeamWorkerClient`].
pub struct BeamDomain<C: BeamWorkerClient> {
    client: C,
}

impl<C: BeamWorkerClient> BeamDomain<C> {
    pub fn new(client: C) -> Self {
        Self { client }
    }

    pub fn client(&self) -> &C {
        &self.client
    }

    /// `invoke` command — synchronous round-trip returning the agent result.
    pub async fn invoke(&self, payload: InvokePayload) -> RiverbaseResult<Value> {
        let request = InvokeRequest {
            agent_name: payload.agent_name,
            content: payload.content,
            session_id: payload.session_id,
            model_override: payload.model_override,
            metadata: payload.metadata,
            interaction_id: None,
            request_id: Some(Uuid::new_v4()),
            stream: payload.stream,
            actions: None,
            auth_context: payload.auth_context,
        };
        let value = serialize_request(&request)?;
        self.client.request("invoke_agent", value).await
    }

    /// `stream` command — fire-and-forget; chunks arrive over the SSE bridge.
    pub async fn stream(&self, payload: InvokePayload) -> RiverbaseResult<StreamAck> {
        let request_id = Uuid::new_v4();
        let request = InvokeRequest {
            agent_name: payload.agent_name.clone(),
            content: payload.content,
            session_id: payload.session_id,
            model_override: payload.model_override,
            metadata: payload.metadata,
            interaction_id: None,
            request_id: Some(request_id),
            stream: true,
            actions: None,
            auth_context: payload.auth_context,
        };
        let value = serialize_request(&request)?;
        self.client.send("invoke_agent", value).await?;
        Ok(StreamAck {
            request_id,
            session_id: payload.session_id,
            agent_name: payload.agent_name,
        })
    }

    /// `resume` command — re-enter an interrupted interaction with action results.
    pub async fn resume(&self, payload: ResumePayload) -> RiverbaseResult<StreamAck> {
        let request_id = Uuid::new_v4();
        let request = InvokeRequest {
            agent_name: payload.agent_name.clone(),
            content: payload.content,
            session_id: payload.session_id,
            model_override: payload.model_override,
            metadata: payload.metadata,
            interaction_id: Some(payload.interaction_id),
            request_id: Some(request_id),
            stream: true,
            actions: Some(payload.actions),
            auth_context: payload.auth_context,
        };
        let value = serialize_request(&request)?;
        self.client.send("invoke_agent", value).await?;
        Ok(StreamAck {
            request_id,
            session_id: payload.session_id,
            agent_name: payload.agent_name,
        })
    }
}

fn serialize_request(request: &InvokeRequest) -> RiverbaseResult<Value> {
    serde_json::to_value(request).map_err(|e| beam_core::BEM_001.with_data(e.to_string()))
}

/// Bridges beam commands to a [`BeamWorkerClient`].
pub struct BeamCommandEngine {
    ctx: EngineContext,
    client: Arc<dyn BeamWorkerClient>,
    authorizer: Option<Arc<dyn ActivityAuthorizer>>,
}

impl BeamCommandEngine {
    #[must_use]
    pub fn new(namespace: impl Into<String>, client: Arc<dyn BeamWorkerClient>) -> Self {
        Self {
            ctx: EngineContext::new(namespace),
            client,
            authorizer: None,
        }
    }

    /// Enforce the beam Casbin policy per command (defense in depth alongside
    /// the HTTP endpoint layer).
    #[must_use]
    pub fn with_authorizer(mut self, authorizer: Arc<dyn ActivityAuthorizer>) -> Self {
        self.authorizer = Some(authorizer);
        self
    }

    /// Authorize a command before dispatch; a denial returns a `ForbiddenError`
    /// (HTTP 403). No-op when no authorizer is configured.
    async fn authorize(&self, cmdkey: &str, payload: &Value) -> RiverbaseResult<()> {
        if let Some(authorizer) = &self.authorizer {
            let subject = subject_from_payload(payload);
            let activity = command_activity(cmdkey, payload);
            authorizer
                .enforce(&ActivityRequest::new(subject, activity))
                .await?;
        }
        Ok(())
    }
}

#[async_trait]
impl DomainCommandEngine for BeamCommandEngine {
    fn context(&self) -> &EngineContext {
        &self.ctx
    }

    async fn commands(&self) -> RiverbaseResult<Vec<String>> {
        Ok(vec![
            CMD_INVOKE.to_string(),
            CMD_STREAM.to_string(),
            CMD_RESUME.to_string(),
        ])
    }

    fn command_meta(&self, cmdkey: &str) -> Option<CommandMeta> {
        match cmdkey {
            CMD_INVOKE => Some(
                CommandMeta::object(CMD_INVOKE, "Invoke Agent")
                    .with_description("Synchronously invoke an agent and return its result."),
            ),
            CMD_STREAM => Some(
                CommandMeta::object(CMD_STREAM, "Stream Agent")
                    .with_description("Start a streaming invocation; chunks arrive over SSE."),
            ),
            CMD_RESUME => Some(
                CommandMeta::object(CMD_RESUME, "Resume Interaction")
                    .with_description("Resume an interrupted interaction with action results."),
            ),
            _ => None,
        }
    }

    async fn execute(
        &self,
        _ctx: &EngineContext,
        cmdkey: &str,
        payload: Value,
        _target: CommandTarget,
    ) -> RiverbaseResult<Value> {
        self.authorize(cmdkey, &payload).await?;
        match cmdkey {
            CMD_INVOKE => self.client.request("invoke_agent", payload).await,
            CMD_STREAM | CMD_RESUME => {
                self.client.send("invoke_agent", payload).await?;
                Ok(json!({ "status": "accepted" }))
            }
            other => Err(beam_core::BEM_024.with_data(other.to_string())),
        }
    }
}

/// Serves the agent / model / session catalog as riverbase query resources.
pub struct BeamQueryEngine {
    ctx: EngineContext,
    catalog: Arc<RwLock<Catalog>>,
}

impl BeamQueryEngine {
    #[must_use]
    pub fn new(namespace: impl Into<String>, catalog: Arc<RwLock<Catalog>>) -> Self {
        Self {
            ctx: EngineContext::new(namespace),
            catalog,
        }
    }
}

#[async_trait]
impl DomainQueryEngine for BeamQueryEngine {
    fn context(&self) -> &EngineContext {
        &self.ctx
    }

    async fn queries(&self) -> RiverbaseResult<Vec<String>> {
        Ok(vec![
            RES_AGENT.to_string(),
            RES_MODEL.to_string(),
            RES_SESSION.to_string(),
        ])
    }

    async fn query_scope_metas(&self) -> RiverbaseResult<Vec<QueryRouteMeta>> {
        Ok(vec![
            QueryRouteMeta {
                resource: RES_AGENT.into(),
                scope: ScopeMeta::none(),
                title: "Agents".into(),
                openapi: OpenApiMeta::default(),
                kind: QueryResourceKind::Query,
                allowed_zones: Vec::new(),
            },
            QueryRouteMeta {
                resource: RES_MODEL.into(),
                scope: ScopeMeta::none(),
                title: "Models".into(),
                openapi: OpenApiMeta::default(),
                kind: QueryResourceKind::Query,
                allowed_zones: Vec::new(),
            },
            QueryRouteMeta {
                resource: RES_SESSION.into(),
                scope: ScopeMeta::none(),
                title: "Agent Sessions".into(),
                openapi: OpenApiMeta::default(),
                kind: QueryResourceKind::Query,
                allowed_zones: Vec::new(),
            },
        ])
    }

    async fn execute(
        &self,
        _ctx: &EngineContext,
        resource: &str,
        access: QueryAccess,
        _request: QueryRequest,
        item_id: Option<&str>,
    ) -> RiverbaseResult<Value> {
        let catalog = self.catalog.read().await;
        let list: Vec<Value> = match resource {
            RES_AGENT => catalog
                .list_agents()
                .iter()
                .map(|a| serde_json::to_value(a).unwrap_or(Value::Null))
                .collect(),
            RES_MODEL => catalog
                .list_models()
                .iter()
                .map(|m| serde_json::to_value(m).unwrap_or(Value::Null))
                .collect(),
            RES_SESSION => catalog
                .list_sessions()
                .iter()
                .map(|s| serde_json::to_value(s).unwrap_or(Value::Null))
                .collect(),
            other => {
                return Err(beam_core::BEM_025.with_data(other.to_string()))
            }
        };

        match access {
            QueryAccess::List => Ok(json!({ "data": list, "meta": { "total": list.len() } })),
            QueryAccess::Item => {
                let id = item_id.unwrap_or_default();
                let found = list.into_iter().find(|row| row_matches(resource, row, id));
                found.ok_or_else(|| beam_core::BEM_026.with_data(format!("{resource}/{id}")))
            }
            QueryAccess::Meta => Ok(json!({ "resource": resource })),
            QueryAccess::Report => Err(beam_core::BEM_006.with_data(resource.to_string())),
        }
    }
}

fn row_matches(resource: &str, row: &Value, id: &str) -> bool {
    let key = if resource == RES_SESSION { "session_id" } else { "name" };
    row.get(key).and_then(Value::as_str) == Some(id)
}

/// A bundled beam domain (`flrs.beam`) over a worker client + catalog.
pub struct BeamDomainBundle {
    namespace: String,
    command: Arc<dyn DomainCommandEngine>,
    query: Arc<dyn DomainQueryEngine>,
}

impl BeamDomainBundle {
    #[must_use]
    pub fn new(client: Arc<dyn BeamWorkerClient>, catalog: Arc<RwLock<Catalog>>) -> Self {
        Self::with_namespace(BEAM_NAMESPACE, client, catalog)
    }

    #[must_use]
    pub fn with_namespace(
        namespace: impl Into<String>,
        client: Arc<dyn BeamWorkerClient>,
        catalog: Arc<RwLock<Catalog>>,
    ) -> Self {
        let namespace = namespace.into();
        Self {
            command: Arc::new(BeamCommandEngine::new(namespace.clone(), client)),
            query: Arc::new(BeamQueryEngine::new(namespace.clone(), catalog)),
            namespace,
        }
    }

    /// Build a bundle whose command engine enforces the beam Casbin policy
    /// per command (the HTTP endpoint layer enforces the same policy).
    #[must_use]
    pub fn with_authorizer(
        client: Arc<dyn BeamWorkerClient>,
        catalog: Arc<RwLock<Catalog>>,
        authorizer: Arc<dyn ActivityAuthorizer>,
    ) -> Self {
        let namespace = BEAM_NAMESPACE.to_string();
        Self {
            command: Arc::new(
                BeamCommandEngine::new(namespace.clone(), client).with_authorizer(authorizer),
            ),
            query: Arc::new(BeamQueryEngine::new(namespace.clone(), catalog)),
            namespace,
        }
    }
}

impl Domain for BeamDomainBundle {
    fn namespace(&self) -> &str {
        &self.namespace
    }

    fn title(&self) -> &str {
        "Beam"
    }

    fn description(&self) -> Option<&str> {
        Some("AI agent invocation domain (invoke, stream, resume).")
    }

    fn command_dyn(&self) -> Arc<dyn DomainCommandEngine> {
        self.command.clone()
    }

    fn query_dyn(&self) -> Arc<dyn DomainQueryEngine> {
        self.query.clone()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    use beam_core::{BeamConfig, RiverBeam};
    use beam_stream::{BeamStream, InMemoryTransport};
    use beam_types::StreamChunkType;
    use beam_worker::BeamWorker;

    use crate::catalog::AgentInfo;
    use crate::client::LocalWorkerClient;

    fn payload(stream: bool) -> InvokePayload {
        InvokePayload {
            agent_name: "demo".into(),
            content: vec![ContentPart::text("hello")],
            session_id: Uuid::new_v4(),
            model_override: None,
            metadata: Value::Null,
            stream,
            auth_context: None,
        }
    }

    fn typed_domain(stream: Option<Arc<BeamStream>>) -> BeamDomain<LocalWorkerClient> {
        let mut beam = RiverBeam::new(BeamConfig::default());
        if let Some(s) = stream {
            beam.set_stream(s);
        }
        beam.register_echo_agent("demo");
        let worker = Arc::new(BeamWorker::new(Arc::new(beam)));
        BeamDomain::new(LocalWorkerClient::new(worker))
    }

    fn bundle() -> BeamDomainBundle {
        let beam = RiverBeam::new(BeamConfig::default());
        beam.register_echo_agent("demo");
        let worker = Arc::new(BeamWorker::new(Arc::new(beam)));
        let client: Arc<dyn BeamWorkerClient> = Arc::new(LocalWorkerClient::new(worker));

        let mut catalog = Catalog::new();
        catalog.set_agents(vec![AgentInfo {
            name: "demo".into(),
            description: "echo".into(),
            supported_modalities: vec!["text".into()],
            version: "1.0.0".into(),
        }]);
        BeamDomainBundle::new(client, Arc::new(RwLock::new(catalog)))
    }

    #[tokio::test]
    async fn invoke_returns_agent_result() {
        let domain = typed_domain(None);
        let out = domain.invoke(payload(false)).await.unwrap();
        assert_eq!(out["agent_name"], "demo");
    }

    #[tokio::test]
    async fn stream_returns_ack_and_publishes_frames() {
        let transport = Arc::new(InMemoryTransport::new());
        let stream = Arc::new(BeamStream::new(transport.clone()));
        let domain = typed_domain(Some(stream));
        let ack = domain.stream(payload(true)).await.unwrap();
        assert_eq!(ack.agent_name, "demo");

        // send() spawns; wait briefly for the background invoke to publish.
        for _ in 0..50 {
            if !transport.frames().await.is_empty() {
                break;
            }
            tokio::time::sleep(std::time::Duration::from_millis(10)).await;
        }
        let frames = transport.frames().await;
        assert!(frames.iter().any(|f| f.frame.chunk_type == StreamChunkType::Done));
    }

    #[tokio::test]
    async fn domain_exposes_commands_and_queries() {
        let domain = bundle();
        assert_eq!(domain.namespace(), "flrs.beam");
        let commands = domain.command_dyn().commands().await.unwrap();
        assert!(commands.contains(&"invoke".to_string()));
        let queries = domain.query_dyn().queries().await.unwrap();
        assert!(queries.contains(&"agent".to_string()));
    }

    #[tokio::test]
    async fn invoke_command_bridges_to_worker() {
        let domain = bundle();
        let payload = json!({
            "agent_name": "demo",
            "content": [{"type": "text", "text": "hi"}],
            "session_id": uuid::Uuid::new_v4().to_string(),
            "stream": false,
        });
        let ctx = EngineContext::new(BEAM_NAMESPACE);
        let out = domain
            .command_dyn()
            .execute(&ctx, "invoke", payload, CommandTarget::collection("agent"))
            .await
            .expect("invoke executes");
        assert_eq!(out["agent_name"], "demo");
    }

    #[tokio::test]
    async fn command_enforces_casbin_policy() {
        use crate::authz::build_beam_authorizer;

        let beam = RiverBeam::new(BeamConfig::default());
        beam.register_echo_agent("demo");
        let worker = Arc::new(BeamWorker::new(Arc::new(beam)));
        let client: Arc<dyn BeamWorkerClient> = Arc::new(LocalWorkerClient::new(worker));
        let catalog = Arc::new(RwLock::new(Catalog::new()));
        let authorizer = build_beam_authorizer().await.expect("authorizer");

        let domain = BeamDomainBundle::with_authorizer(client, catalog, authorizer);
        let ctx = EngineContext::new(BEAM_NAMESPACE);
        let base = json!({
            "agent_name": "demo",
            "content": [{"type": "text", "text": "hi"}],
            "session_id": uuid::Uuid::new_v4().to_string(),
            "stream": false,
        });

        // Anonymous (no role) is denied at the per-command layer.
        let denied = domain
            .command_dyn()
            .execute(&ctx, "invoke", base.clone(), CommandTarget::collection("agent"))
            .await;
        assert!(denied.is_err(), "anonymous invoke must be denied");

        // alice is beam-admin via the policy's g row → allowed.
        let mut allowed_payload = base;
        allowed_payload["auth_context"] = json!({"user_id": "alice"});
        let allowed = domain
            .command_dyn()
            .execute(&ctx, "invoke", allowed_payload, CommandTarget::collection("agent"))
            .await
            .expect("alice invoke allowed");
        assert_eq!(allowed["agent_name"], "demo");
    }

    #[tokio::test]
    async fn agent_query_lists_catalog() {
        let domain = bundle();
        let ctx = EngineContext::new(BEAM_NAMESPACE);
        let out = domain
            .query_dyn()
            .execute(&ctx, "agent", QueryAccess::List, QueryRequest::default(), None)
            .await
            .expect("query executes");
        assert_eq!(out["data"][0]["name"], "demo");
    }
}
