// Error catalogue for riverbeam (`BEM-*`). Shared with leaf crates via include!
// so they can raise specs without depending on beam_core (that would cycle).

riverbase_core::declare_errors! {
    type_base: "https://riverbase.io/~/rs/error/",

    BEM_001 {
        status: 422,
        title: "Unprocessable Content",
        code: "BEM-001",
        message: "Failed to serialize the beam invoke request.",
    },
    BEM_002 {
        status: 422,
        title: "Unprocessable Content",
        code: "BEM-002",
        message: "Failed to encode the worker task payload for NATS.",
    },
    BEM_003 {
        status: 422,
        title: "Unprocessable Content",
        code: "BEM-003",
        message: "The invoke_agent worker payload is not a valid invoke request.",
    },
    BEM_004 {
        status: 422,
        title: "Unprocessable Content",
        code: "BEM-004",
        message: "Knowledge ingest requires inline text; media and URL ingest are host-bound.",
    },
    BEM_005 {
        status: 422,
        title: "Unprocessable Content",
        code: "BEM-005",
        message: "Knowledge delete requires a valid document_id.",
    },
    BEM_006 {
        status: 422,
        title: "Unprocessable Content",
        code: "BEM-006",
        message: "Report queries are not supported for this beam resource.",
    },

    BEM_020 {
        status: 404,
        title: "Not Found",
        code: "BEM-020",
        message: "That agent is not registered.",
    },
    BEM_021 {
        status: 404,
        title: "Not Found",
        code: "BEM-021",
        message: "That agent is not registered for stream dispatch.",
    },
    BEM_022 {
        status: 404,
        title: "Not Found",
        code: "BEM-022",
        message: "The invoke pipeline could not resolve the requested agent.",
    },
    BEM_023 {
        status: 404,
        title: "Not Found",
        code: "BEM-023",
        message: "That agent is not in the beam catalog.",
    },
    BEM_024 {
        status: 404,
        title: "Not Found",
        code: "BEM-024",
        message: "That command is not registered in the beam domain.",
    },
    BEM_025 {
        status: 404,
        title: "Not Found",
        code: "BEM-025",
        message: "That query resource is not registered in the beam domain.",
    },
    BEM_026 {
        status: 404,
        title: "Not Found",
        code: "BEM-026",
        message: "That catalog item was not found.",
    },
    BEM_027 {
        status: 404,
        title: "Not Found",
        code: "BEM-027",
        message: "That agent action was not found.",
    },
    BEM_028 {
        status: 404,
        title: "Not Found",
        code: "BEM-028",
        message: "That agent action could not be resolved because it was not found.",
    },

    BEM_040 {
        status: 400,
        title: "Bad Request",
        code: "BEM-040",
        message: "The agent does not support the requested input modalities.",
    },
    BEM_041 {
        status: 422,
        title: "Unprocessable Content",
        code: "BEM-041",
        message: "No model is available for this request.",
    },
    BEM_042 {
        status: 500,
        title: "Internal Server Error",
        code: "BEM-042",
        message: "The selected model configuration is invalid.",
    },
    BEM_043 {
        status: 500,
        title: "Internal Server Error",
        code: "BEM-043",
        message: "Failed to read the model routing YAML file.",
    },
    BEM_044 {
        status: 500,
        title: "Internal Server Error",
        code: "BEM-044",
        message: "Failed to parse the model routing YAML file.",
    },
    BEM_045 {
        status: 501,
        title: "Not Implemented",
        code: "BEM-045",
        message: "The knowledge subsystem is not configured on this worker.",
    },
    BEM_046 {
        status: 500,
        title: "Internal Server Error",
        code: "BEM-046",
        message: "Failed to serialize the agent invoke result.",
    },
    BEM_047 {
        status: 500,
        title: "Internal Server Error",
        code: "BEM-047",
        message: "Failed to serialize the knowledge ingest result.",
    },

    BEM_060 {
        status: 403,
        title: "Forbidden",
        code: "BEM-060",
        message: "The usage quota for this request has been exceeded.",
    },
    BEM_061 {
        status: 403,
        title: "Forbidden",
        code: "BEM-061",
        message: "A security rule blocked this request.",
    },
    BEM_062 {
        status: 400,
        title: "Bad Request",
        code: "BEM-062",
        message: "Resume requires the pending interaction identifier.",
    },
    BEM_063 {
        status: 400,
        title: "Bad Request",
        code: "BEM-063",
        message: "Resume received an invalid action identifier.",
    },
    BEM_064 {
        status: 400,
        title: "Bad Request",
        code: "BEM-064",
        message: "Resume referenced an unknown pending action.",
    },
    BEM_065 {
        status: 400,
        title: "Bad Request",
        code: "BEM-065",
        message: "Resume action does not belong to the pending interaction.",
    },
    BEM_066 {
        status: 400,
        title: "Bad Request",
        code: "BEM-066",
        message: "Resume action is not pending.",
    },
    BEM_067 {
        status: 403,
        title: "Forbidden",
        code: "BEM-067",
        message: "This beam command is not allowed for the current subject.",
    },

    BEM_080 {
        status: 422,
        title: "Unprocessable Content",
        code: "BEM-080",
        message: "The scripted completion client lock was poisoned.",
    },
    BEM_081 {
        status: 422,
        title: "Unprocessable Content",
        code: "BEM-081",
        message: "The scripted completion client has no remaining steps.",
    },
    BEM_082 {
        status: 422,
        title: "Unprocessable Content",
        code: "BEM-082",
        message: "The language-model completion request failed.",
    },
    BEM_083 {
        status: 422,
        title: "Unprocessable Content",
        code: "BEM-083",
        message: "The language-model completion response could not be decoded.",
    },
    BEM_084 {
        status: 422,
        title: "Unprocessable Content",
        code: "BEM-084",
        message: "The language-model completion returned an error status.",
    },
    BEM_085 {
        status: 422,
        title: "Unprocessable Content",
        code: "BEM-085",
        message: "The language-model completion response has no choices.",
    },
    BEM_086 {
        status: 422,
        title: "Unprocessable Content",
        code: "BEM-086",
        message: "The agent stream ended without a terminal done frame.",
    },
    BEM_087 {
        status: 422,
        title: "Unprocessable Content",
        code: "BEM-087",
        message: "The agent stream reported an error frame.",
    },
    BEM_088 {
        status: 422,
        title: "Unprocessable Content",
        code: "BEM-088",
        message: "The agent tool loop exceeded the maximum number of steps.",
    },
    BEM_089 {
        status: 422,
        title: "Unprocessable Content",
        code: "BEM-089",
        message: "The agent requested an unknown tool during the tool loop.",
    },
    BEM_090 {
        status: 422,
        title: "Unprocessable Content",
        code: "BEM-090",
        message: "The agent requested an unknown tool while resuming actions.",
    },
    BEM_091 {
        status: 404,
        title: "Not Found",
        code: "BEM-091",
        message: "That worker task is not registered.",
    },
    BEM_092 {
        status: 501,
        title: "Not Implemented",
        code: "BEM-092",
        message: "That worker memory task is not implemented yet.",
    },
    BEM_093 {
        status: 500,
        title: "Internal Server Error",
        code: "BEM-093",
        message: "The worker failed to connect to NATS.",
    },
    BEM_094 {
        status: 500,
        title: "Internal Server Error",
        code: "BEM-094",
        message: "The worker failed to subscribe to NATS task subjects.",
    },
    BEM_095 {
        status: 500,
        title: "Internal Server Error",
        code: "BEM-095",
        message: "The domain client failed to connect to NATS.",
    },
    BEM_096 {
        status: 500,
        title: "Internal Server Error",
        code: "BEM-096",
        message: "The domain client failed to request a worker task over NATS.",
    },
    BEM_097 {
        status: 500,
        title: "Internal Server Error",
        code: "BEM-097",
        message: "The domain client failed to publish a worker task over NATS.",
    },
    BEM_098 {
        status: 500,
        title: "Internal Server Error",
        code: "BEM-098",
        message: "The worker reply payload is not valid JSON.",
    },
    BEM_099 {
        status: 500,
        title: "Internal Server Error",
        code: "BEM-099",
        message: "The worker reply envelope is missing a result or a structured error.",
    },
    BEM_100 {
        status: 500,
        title: "Internal Server Error",
        code: "BEM-100",
        message: "The worker error payload is not a structured Riverbase error.",
    },
    BEM_101 {
        status: 500,
        title: "Internal Server Error",
        code: "BEM-101",
        message: "The stream transport failed to connect to NATS.",
    },
    BEM_102 {
        status: 500,
        title: "Internal Server Error",
        code: "BEM-102",
        message: "The stream transport failed to subscribe to a NATS channel.",
    },
    BEM_103 {
        status: 500,
        title: "Internal Server Error",
        code: "BEM-103",
        message: "Failed to serialize a stream frame for NATS.",
    },
    BEM_104 {
        status: 500,
        title: "Internal Server Error",
        code: "BEM-104",
        message: "Failed to publish a stream frame to NATS.",
    },
    BEM_105 {
        status: 422,
        title: "Unprocessable Content",
        code: "BEM-105",
        message: "Failed to publish an agent stream chunk.",
    },
    BEM_106 {
        status: 422,
        title: "Unprocessable Content",
        code: "BEM-106",
        message: "Failed to publish the agent stream completion frame.",
    },
    BEM_107 {
        status: 422,
        title: "Unprocessable Content",
        code: "BEM-107",
        message: "Sandbox tools require metadata.sandbox_root when no working tree is bound.",
    },
    BEM_108 {
        status: 422,
        title: "Unprocessable Content",
        code: "BEM-108",
        message: "A required sandbox tool argument is missing.",
    },
    BEM_109 {
        status: 501,
        title: "Not Implemented",
        code: "BEM-109",
        message: "The remember tool must be bound by the host memory manager.",
    },

    BEM_110 {
        status: 500,
        title: "Internal Server Error",
        code: "BEM-110",
        message: "Failed to establish the beam store database pool.",
    },
    BEM_111 {
        status: 500,
        title: "Internal Server Error",
        code: "BEM-111",
        message: "Could not get a database connection to apply beam store schema.",
    },
    BEM_112 {
        status: 500,
        title: "Internal Server Error",
        code: "BEM-112",
        message: "Failed to apply the beam store schema.",
    },
    BEM_113 {
        status: 500,
        title: "Internal Server Error",
        code: "BEM-113",
        message: "Could not get a database connection for the beam store.",
    },
    BEM_114 {
        status: 500,
        title: "Internal Server Error",
        code: "BEM-114",
        message: "Failed to check in beam agents.",
    },
    BEM_115 {
        status: 500,
        title: "Internal Server Error",
        code: "BEM-115",
        message: "Failed to check in beam models.",
    },
    BEM_116 {
        status: 500,
        title: "Internal Server Error",
        code: "BEM-116",
        message: "Failed to ensure a beam session row.",
    },
    BEM_117 {
        status: 500,
        title: "Internal Server Error",
        code: "BEM-117",
        message: "Failed to update beam session activity.",
    },
    BEM_118 {
        status: 500,
        title: "Internal Server Error",
        code: "BEM-118",
        message: "Failed to create a beam interaction.",
    },
    BEM_119 {
        status: 500,
        title: "Internal Server Error",
        code: "BEM-119",
        message: "Failed to complete a beam interaction.",
    },
    BEM_120 {
        status: 500,
        title: "Internal Server Error",
        code: "BEM-120",
        message: "Failed to create a beam run.",
    },
    BEM_121 {
        status: 500,
        title: "Internal Server Error",
        code: "BEM-121",
        message: "Failed to complete a beam run.",
    },
    BEM_122 {
        status: 500,
        title: "Internal Server Error",
        code: "BEM-122",
        message: "Failed to save a beam message.",
    },
    BEM_123 {
        status: 500,
        title: "Internal Server Error",
        code: "BEM-123",
        message: "Failed to allocate the next beam message sequence.",
    },
    BEM_124 {
        status: 500,
        title: "Internal Server Error",
        code: "BEM-124",
        message: "Failed to create a beam action.",
    },
    BEM_125 {
        status: 500,
        title: "Internal Server Error",
        code: "BEM-125",
        message: "Failed to load a beam action.",
    },
    BEM_126 {
        status: 500,
        title: "Internal Server Error",
        code: "BEM-126",
        message: "Failed to resolve a beam action.",
    },
    BEM_127 {
        status: 500,
        title: "Internal Server Error",
        code: "BEM-127",
        message: "Failed to load a beam session.",
    },
    BEM_128 {
        status: 500,
        title: "Internal Server Error",
        code: "BEM-128",
        message: "Failed to load a beam interaction.",
    },
    BEM_129 {
        status: 500,
        title: "Internal Server Error",
        code: "BEM-129",
        message: "Failed to load a beam run.",
    },
    BEM_130 {
        status: 500,
        title: "Internal Server Error",
        code: "BEM-130",
        message: "Failed to list beam messages.",
    },
    BEM_131 {
        status: 500,
        title: "Internal Server Error",
        code: "BEM-131",
        message: "The in-memory beam store write lock was poisoned.",
    },
    BEM_132 {
        status: 500,
        title: "Internal Server Error",
        code: "BEM-132",
        message: "The in-memory beam store read lock was poisoned.",
    },

    BEM_140 {
        status: 500,
        title: "Internal Server Error",
        code: "BEM-140",
        message: "The in-memory memory backend could not load a layer because the lock was poisoned.",
    },
    BEM_141 {
        status: 500,
        title: "Internal Server Error",
        code: "BEM-141",
        message: "The in-memory memory backend could not append a layer because the lock was poisoned.",
    },
    BEM_142 {
        status: 500,
        title: "Internal Server Error",
        code: "BEM-142",
        message: "The in-memory memory backend could not forget an item because the lock was poisoned.",
    },

    BEM_200 {
        status: 500,
        title: "Internal Server Error",
        code: "BEM-200",
        message: "The in-memory knowledge store could not upsert records because the lock was poisoned.",
    },
    BEM_201 {
        status: 500,
        title: "Internal Server Error",
        code: "BEM-201",
        message: "The in-memory knowledge store could not query records because the lock was poisoned.",
    },
    BEM_202 {
        status: 500,
        title: "Internal Server Error",
        code: "BEM-202",
        message: "The in-memory knowledge store could not delete records because the lock was poisoned.",
    },
    BEM_203 {
        status: 500,
        title: "Internal Server Error",
        code: "BEM-203",
        message: "Failed to establish the knowledge store database pool.",
    },
    BEM_204 {
        status: 500,
        title: "Internal Server Error",
        code: "BEM-204",
        message: "Could not get a database connection for the knowledge store.",
    },
    BEM_205 {
        status: 500,
        title: "Internal Server Error",
        code: "BEM-205",
        message: "Could not get a database connection to apply knowledge schema.",
    },
    BEM_206 {
        status: 500,
        title: "Internal Server Error",
        code: "BEM-206",
        message: "Failed to apply the knowledge store schema.",
    },
    BEM_207 {
        status: 422,
        title: "Unprocessable Content",
        code: "BEM-207",
        message: "A knowledge record is missing a document_id UUID.",
    },
    BEM_208 {
        status: 500,
        title: "Internal Server Error",
        code: "BEM-208",
        message: "Failed to upsert a knowledge document row.",
    },
    BEM_209 {
        status: 500,
        title: "Internal Server Error",
        code: "BEM-209",
        message: "Failed to upsert a knowledge chunk row.",
    },
    BEM_210 {
        status: 500,
        title: "Internal Server Error",
        code: "BEM-210",
        message: "Failed to upsert a knowledge memory row.",
    },
    BEM_211 {
        status: 500,
        title: "Internal Server Error",
        code: "BEM-211",
        message: "Failed to query knowledge chunks.",
    },
    BEM_212 {
        status: 500,
        title: "Internal Server Error",
        code: "BEM-212",
        message: "Failed to query knowledge memory rows.",
    },
    BEM_213 {
        status: 500,
        title: "Internal Server Error",
        code: "BEM-213",
        message: "Failed to delete a knowledge chunk by id.",
    },
    BEM_214 {
        status: 500,
        title: "Internal Server Error",
        code: "BEM-214",
        message: "Failed to delete knowledge chunks by document.",
    },
    BEM_215 {
        status: 500,
        title: "Internal Server Error",
        code: "BEM-215",
        message: "Failed to delete a knowledge memory row.",
    },
    BEM_220 {
        status: 500,
        title: "Internal Server Error",
        code: "BEM-220",
        message: "The embedder returned an empty result for the query text.",
    },
    BEM_221 {
        status: 500,
        title: "Internal Server Error",
        code: "BEM-221",
        message: "The embedder HTTP request failed.",
    },
    BEM_222 {
        status: 500,
        title: "Internal Server Error",
        code: "BEM-222",
        message: "The embedder HTTP response could not be decoded.",
    },
    BEM_223 {
        status: 500,
        title: "Internal Server Error",
        code: "BEM-223",
        message: "The embedder HTTP request returned an error status.",
    },
    BEM_224 {
        status: 500,
        title: "Internal Server Error",
        code: "BEM-224",
        message: "The embedder response is missing the data array.",
    },
    BEM_225 {
        status: 500,
        title: "Internal Server Error",
        code: "BEM-225",
        message: "The embedder response is missing an embedding array.",
    },
    BEM_226 {
        status: 500,
        title: "Internal Server Error",
        code: "BEM-226",
        message: "An embedding vector width does not match the configured dimension.",
    },
    BEM_227 {
        status: 500,
        title: "Internal Server Error",
        code: "BEM-227",
        message: "The embedder returned a different number of embeddings than requested.",
    },
    BEM_230 {
        status: 422,
        title: "Unprocessable Content",
        code: "BEM-230",
        message: "Knowledge ingest produced no chunks.",
    },
    BEM_231 {
        status: 500,
        title: "Internal Server Error",
        code: "BEM-231",
        message: "An HTTP embedder was requested without an API key.",
        hint: "Set BEAM_API_KEY, GFS_BEAM_API_KEY, or NVIDIA_API_KEY.",
    },
    BEM_232 {
        status: 500,
        title: "Internal Server Error",
        code: "BEM-232",
        message: "HashEmbedder cannot write into a pgvector store.",
    },
    BEM_233 {
        status: 500,
        title: "Internal Server Error",
        code: "BEM-233",
        message: "The embedder dimension does not match KNOWLEDGE_EMBEDDING_DIM.",
    },
    BEM_234 {
        status: 500,
        title: "Internal Server Error",
        code: "BEM-234",
        message: "pgvector knowledge storage requires a 1536-dimension embedding.",
    },

    BEM_300 {
        status: 400,
        title: "Bad Request",
        code: "BEM-300",
        message: "The sandbox path is absolute, contains NUL, or uses a forbidden separator.",
    },
    BEM_301 {
        status: 400,
        title: "Bad Request",
        code: "BEM-301",
        message: "The sandbox path contains a parent-directory component.",
    },
    BEM_302 {
        status: 400,
        title: "Bad Request",
        code: "BEM-302",
        message: "The resolved sandbox path escapes the jail.",
    },
    BEM_303 {
        status: 400,
        title: "Bad Request",
        code: "BEM-303",
        message: "The sandbox parent path escapes the jail.",
    },
    BEM_304 {
        status: 400,
        title: "Bad Request",
        code: "BEM-304",
        message: "The sandbox path is missing a file name.",
    },
    BEM_305 {
        status: 400,
        title: "Bad Request",
        code: "BEM-305",
        message: "The joined sandbox path is not under the jail root.",
    },
    BEM_306 {
        status: 400,
        title: "Bad Request",
        code: "BEM-306",
        message: "The sandbox path is not a directory.",
    },
    BEM_307 {
        status: 500,
        title: "Internal Server Error",
        code: "BEM-307",
        message: "Failed to read a file inside the sandbox.",
    },
    BEM_308 {
        status: 400,
        title: "Bad Request",
        code: "BEM-308",
        message: "Creating the sandbox write parent escaped the jail.",
    },
    BEM_309 {
        status: 400,
        title: "Bad Request",
        code: "BEM-309",
        message: "A listed sandbox path could not be stripped to a jail-relative path.",
    },
    BEM_310 {
        status: 500,
        title: "Internal Server Error",
        code: "BEM-310",
        message: "Failed to create the sandbox root directory.",
    },
    BEM_311 {
        status: 500,
        title: "Internal Server Error",
        code: "BEM-311",
        message: "Failed to canonicalize the sandbox root.",
    },
    BEM_312 {
        status: 500,
        title: "Internal Server Error",
        code: "BEM-312",
        message: "Failed to canonicalize an existing sandbox path.",
    },
    BEM_313 {
        status: 500,
        title: "Internal Server Error",
        code: "BEM-313",
        message: "Failed to canonicalize a sandbox parent path.",
    },
    BEM_314 {
        status: 500,
        title: "Internal Server Error",
        code: "BEM-314",
        message: "Failed to create directories while writing a sandbox file.",
    },
    BEM_315 {
        status: 500,
        title: "Internal Server Error",
        code: "BEM-315",
        message: "Failed to canonicalize a sandbox write parent.",
    },
    BEM_316 {
        status: 500,
        title: "Internal Server Error",
        code: "BEM-316",
        message: "Failed to write a file inside the sandbox.",
    },
    BEM_317 {
        status: 500,
        title: "Internal Server Error",
        code: "BEM-317",
        message: "Failed to read a sandbox directory entry.",
    },
    BEM_318 {
        status: 500,
        title: "Internal Server Error",
        code: "BEM-318",
        message: "Failed to read a sandbox directory listing.",
    },
    BEM_320 {
        status: 500,
        title: "Internal Server Error",
        code: "BEM-320",
        message: "Failed to initialize a git repository in the sandbox.",
    },
    BEM_321 {
        status: 500,
        title: "Internal Server Error",
        code: "BEM-321",
        message: "Failed to open the sandbox git repository.",
    },
    BEM_322 {
        status: 500,
        title: "Internal Server Error",
        code: "BEM-322",
        message: "Failed to read git status in the sandbox.",
    },
    BEM_323 {
        status: 500,
        title: "Internal Server Error",
        code: "BEM-323",
        message: "Failed to compute a git diff in the sandbox.",
    },
    BEM_324 {
        status: 500,
        title: "Internal Server Error",
        code: "BEM-324",
        message: "Failed to read the git log in the sandbox.",
    },
    BEM_325 {
        status: 500,
        title: "Internal Server Error",
        code: "BEM-325",
        message: "Failed to stage files in the sandbox git repository.",
    },
    BEM_326 {
        status: 500,
        title: "Internal Server Error",
        code: "BEM-326",
        message: "Failed to create a git commit in the sandbox.",
    },
    BEM_327 {
        status: 500,
        title: "Internal Server Error",
        code: "BEM-327",
        message: "Failed to read the current git branch in the sandbox.",
    },
    BEM_328 {
        status: 403,
        title: "Forbidden",
        code: "BEM-328",
        message: "Pushing a protected git ref is not allowed.",
    },
    BEM_329 {
        status: 500,
        title: "Internal Server Error",
        code: "BEM-329",
        message: "The sandbox git repository has no origin remote.",
    },
    BEM_330 {
        status: 500,
        title: "Internal Server Error",
        code: "BEM-330",
        message: "Failed to push a git ref from the sandbox.",
    },
    BEM_331 {
        status: 500,
        title: "Internal Server Error",
        code: "BEM-331",
        message: "Failed to add or update the sandbox git origin remote.",
    },
    BEM_332 {
        status: 500,
        title: "Internal Server Error",
        code: "BEM-332",
        message: "Failed to check out a git branch in the sandbox.",
    },

    BEM_350 {
        status: 400,
        title: "Bad Request",
        code: "BEM-350",
        message: "The audio bytes are missing a RIFF/WAVE header.",
    },
    BEM_351 {
        status: 400,
        title: "Bad Request",
        code: "BEM-351",
        message: "The WAV payload has no data chunk.",
    },
    BEM_352 {
        status: 422,
        title: "Unprocessable Content",
        code: "BEM-352",
        message: "WebM or MP4 decode requires a host decoder; fixture tests use WAV.",
    },
    BEM_353 {
        status: 422,
        title: "Unprocessable Content",
        code: "BEM-353",
        message: "The audio container is not supported.",
    },
    BEM_354 {
        status: 422,
        title: "Unprocessable Content",
        code: "BEM-354",
        message: "The audio turn received empty audio bytes.",
    },
    BEM_355 {
        status: 500,
        title: "Internal Server Error",
        code: "BEM-355",
        message: "HTTP speech-to-text requires a base URL.",
    },
    BEM_356 {
        status: 500,
        title: "Internal Server Error",
        code: "BEM-356",
        message: "Failed to build the speech-to-text multipart body.",
    },
    BEM_357 {
        status: 500,
        title: "Internal Server Error",
        code: "BEM-357",
        message: "The speech-to-text HTTP request failed.",
    },
    BEM_358 {
        status: 500,
        title: "Internal Server Error",
        code: "BEM-358",
        message: "The speech-to-text HTTP response could not be decoded.",
    },
    BEM_359 {
        status: 500,
        title: "Internal Server Error",
        code: "BEM-359",
        message: "The speech-to-text HTTP request returned an error status.",
    },
    BEM_360 {
        status: 500,
        title: "Internal Server Error",
        code: "BEM-360",
        message: "The audio turn failed to invoke the agent.",
    },
}
